apiVersion: skaffold/v2beta16
kind: Config
requires:
  - configs: ["infra"]
    path: infra/skaffold.yaml
  - configs: ["user-management-service"]
    path: userManagementService/skaffold.yaml
  - configs: ["event-management-service"]
    path: eventLoggingService/skaffold.yaml
  - configs: ["jobportal-service"]
    path: jobsPortalService/skaffold.yaml
build: {}
deploy: {}
