image: jobportal.azurecr.io/user-management-service:v1
pullPolicy: Always

replicas: 1

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

env:
  - name: RABBITMQ_USER
    value: "user"
  - name: RABBITMQ_PASSWORD
    value: "local-password"
  - name: RABBITMQ_HOST
    value: "rabbitmq"
  - name: APP_SECRET_KEY
    value: "secret"
  - name: MONGODB_HOST
    value: "mongodb"