image: jobportal.azurecr.io/event-management-service:v1
pullPolicy: IfNotPresent

replicas: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: RABBITMQ_USER
    value: "user"
  - name: RABBITMQ_PASSWORD
    value: "local-password"
  - name: RABBITMQ_HOST
    value: "rabbitmq"
  - name: MONGODB_HOST
    value: "mongodb"