apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-management-service
  name: user-management-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
        - name: user-management-service
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          env:
  {{- toYaml .Values.env | nindent 12 }}