apiVersion: v1
kind: Service
metadata:
  labels:
    app: statistics-service
  name: statistics-service
spec:
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: statistics-service
  type: ClusterIP