apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobportal-service
  name: jobportal-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: jobportal-service
