image: jobportal.azurecr.io/statistics-service:v1
pullPolicy: Always

replicas: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  - name: EVENT_MANAGEMENT_SERVICE_URL
    value: "http://event-management-service:4000"